# Generated by Django 5.1.1 on 2024-10-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_pedido_cafe_te_alter_pedido_guarnicion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='bebida',
            name='adicionales',
            field=models.ManyToManyField(blank=True, to='App.adicional'),
        ),
        migrations.AddField(
            model_name='cafete',
            name='adicionales',
            field=models.ManyToManyField(blank=True, to='App.adicional'),
        ),
        migrations.AddField(
            model_name='comida',
            name='adicionales',
            field=models.ManyToManyField(blank=True, to='App.adicional'),
        ),
        migrations.AddField(
            model_name='guarnicion',
            name='adicionales',
            field=models.ManyToManyField(blank=True, to='App.adicional'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='adicionales',
            field=models.ManyToManyField(blank=True, to='App.adicional'),
        ),
        migrations.AddField(
            model_name='postre',
            name='adicionales',
            field=models.ManyToManyField(blank=True, to='App.adicional'),
        ),
    ]
