# Generated by Django 5.1.1 on 2024-10-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_mesa_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='numero_mesa',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='sector',
            field=models.CharField(max_length=100),
        ),
    ]
