# Generated by Django 5.1.1 on 2024-10-26 08:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_mesa_numero_mesa_alter_mesa_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido_Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('adicional_bebida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adicionales_bebida_cliente', to='App.adicional')),
                ('adicional_cafe_te', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adicionales_cafe_te_cliente', to='App.adicional')),
                ('adicional_guarnicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adicionales_guarnicion_cliente', to='App.adicional')),
                ('adicional_plato_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adicionales_plato_cliente', to='App.adicional')),
                ('adicional_postre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adicionales_postre_cliente', to='App.adicional')),
                ('bebida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.bebida')),
                ('cafe_te', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.cafete')),
                ('guarnicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.guarnicion')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.mesa')),
                ('plato_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.comida')),
                ('postre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.postre')),
            ],
        ),
    ]
